# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecd941af80ad4aee528b79ce68c871e24b29a2568e391370f4208b7b3850aa04e5b67b39c2d2f0de6e2e7b5ee531c64ddc4450fbec06f58ea2f12ebb684fdc78

test:
  secret_key_base: 4e68caee193a9a7930fc473f3c23680618e4bcbc4a02b6f09f8d43939f6d61bfcdd3073e94494cf6db4491eb51104e04a6c9a1bc14c337b396c973d3d51d1dd4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
